# Generated by Django 2.2.17 on 2021-01-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adr',
            field=models.CharField(default=2, max_length=122),
            preserve_default=False,
        ),
    ]
