# Generated by Django 2.2.17 on 2021-01-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_adr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adr',
            field=models.CharField(default='ratanpur', max_length=122),
        ),
    ]
